# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myenv < Formula
  desc ""
  homepage ""
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takashiraki/myenv/releases/download/v0.6.1/myenv_Darwin_x86_64.tar.gz"
      sha256 "f12d09b51f2dc6f2479fdf4dfeccbfd69f37504e6c40fb279af3907d35bd4c87"

      def install
        bin.install "myenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takashiraki/myenv/releases/download/v0.6.1/myenv_Darwin_arm64.tar.gz"
      sha256 "fb0dc7ac59985342127778ec49555626edbb572506fc3dffcc5ab90ec5dd06ed"

      def install
        bin.install "myenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takashiraki/myenv/releases/download/v0.6.1/myenv_Linux_x86_64.tar.gz"
      sha256 "4ab8e49bf55d3068c7ba8d8152cc227b30e0fa3a403cf63f1251458900de4854"
      def install
        bin.install "myenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takashiraki/myenv/releases/download/v0.6.1/myenv_Linux_arm64.tar.gz"
      sha256 "43952c54d0296ee02f74f2bb8d3cc088ceae32b0ee4e650b67e17e815ba560e2"
      def install
        bin.install "myenv"
      end
    end
  end
end
