# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myenv < Formula
  desc ""
  homepage ""
  version "0.7.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takashiraki/myenv/releases/download/v0.7.2/myenv_Darwin_x86_64.tar.gz"
      sha256 "db1c1fff70d983b24a39f9baa82760f49a59cb0d651ce19f9a2b4ccd25662df9"

      def install
        bin.install "myenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takashiraki/myenv/releases/download/v0.7.2/myenv_Darwin_arm64.tar.gz"
      sha256 "b5f267a8406077b57b0f7c171f4c95ac92ecbc71a160ed58855be856504bc25e"

      def install
        bin.install "myenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takashiraki/myenv/releases/download/v0.7.2/myenv_Linux_x86_64.tar.gz"
      sha256 "6af3cdf28fda186a0eb0619e841ee656ac8bda953590057b355f6beb83031c51"
      def install
        bin.install "myenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takashiraki/myenv/releases/download/v0.7.2/myenv_Linux_arm64.tar.gz"
      sha256 "9bc40fe62d2a0699c1c1b6cbf12e2a5913e86a2da93426560fc22db105858918"
      def install
        bin.install "myenv"
      end
    end
  end
end
