# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myenv < Formula
  desc ""
  homepage ""
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takashiraki/myenv/releases/download/v0.6.0/myenv_Darwin_x86_64.tar.gz"
      sha256 "50fc14bce5e42e932a75471a3c4e65abed8d426550aa119b7db4514795dbfaaa"

      def install
        bin.install "myenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takashiraki/myenv/releases/download/v0.6.0/myenv_Darwin_arm64.tar.gz"
      sha256 "847c9b9722cab774eb035bf6b25bffb869818557c3af63938186a28c7d841655"

      def install
        bin.install "myenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takashiraki/myenv/releases/download/v0.6.0/myenv_Linux_x86_64.tar.gz"
      sha256 "1f4088f79f2d7712d9902df21002c4299582961e43ae1c82ab5315dff6ded1c3"
      def install
        bin.install "myenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takashiraki/myenv/releases/download/v0.6.0/myenv_Linux_arm64.tar.gz"
      sha256 "6184e3426600b1133c8e3fed9add41726a178afe4c337ba407bd9063a97413f7"
      def install
        bin.install "myenv"
      end
    end
  end
end
